#!/bin/bash
# script: systeminforeport.sh
# author: Tiojang Chando Junior John

#exit if a command status is non-zero and hide error output
set -e

#get hostname,username and date/time for report
HOST=$(hostname)
USER_NAME=$(whoami)
DATE_TIME=$(date +"%Y/%M/%D %H:%M:%S")

#report OS name and Version
OS_INFO="$PRETTY_NAME"

# Get human-readable system uptime.
UPTIME=$(uptime -p)

# Get total installed RAM size in human-readable format.
RAM_SIZE=$(free -h | grep "Mem:" | awk '{print $2}')

# Get video card product name 
VIDEO_CARD=$(lshw -C display 2>/dev/null | grep product: | awk '{print $2}' | head -1)

# Determine the interface connected to the default gateway.
DEFAULT_IFACE=$(ip route show default | awk "{print $5}" | head -1)

# Get the Host IP address for the default interface
HOST_IP=$(ip a show "$DEFAULT_IFACE" 2>/dev/null | grep inet | awk '{print $2}' | cut -d/ -f1 | head -1)
# Create a comma-separated list of unique users currently logged in.
USER_LIST=$(who | awk '{print $1}' | sort -u | tr '\n' ',' | sed 's/,$//')

# Format Disk Space as requested: /MOUNTPOINT N.
DISK_FREE_INFO=$(df -hT --local | awk 'NR==1 {print ""} NR>1 {print $7 " " $5}')

# Prints a blank line before the report.
echo ""

cat << EOF
System Report for $HOST generated by $USER_NAME, on $DATE_TIME
 
System Information
------------------
OS: $OS_INFO
Uptime: $UPTIME
RAM: $RAM_SIZE
Disk(s): $DISK_INFO
Video: $VIDEO_CARD
Host Address: $HOST_IP
 
System Status
-------------
Users Logged In: $USER_LIST
Disk Space:
$DISK_FREE_INFO
EOF

# Prints a blank line after the report.
echo ""
